"""Migración inicial

Revision ID: 36eabc2381ac
Revises: 
Create Date: 2024-12-04 20:24:04.833406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36eabc2381ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('advisor_name', sa.String(), nullable=True),
    sa.Column('career', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.drop_index('ix_system_info_host', table_name='system_info')
    op.drop_index('ix_system_info_id', table_name='system_info')
    op.drop_table('system_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('disk_usage', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('top_processes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('failed_services', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('uptime', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('network_info', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('connections', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('swap_usage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_logs', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_info_pkey')
    )
    op.create_index('ix_system_info_id', 'system_info', ['id'], unique=False)
    op.create_index('ix_system_info_host', 'system_info', ['host'], unique=False)
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
