"""Migración cuarta

Revision ID: 955339eb73dd
Revises: f6aea54e106e
Create Date: 2024-12-05 09:42:59.692154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955339eb73dd'
down_revision: Union[str, None] = 'f6aea54e106e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('disk_usage', sa.String(), nullable=True),
    sa.Column('top_processes', sa.String(), nullable=True),
    sa.Column('failed_services', sa.String(), nullable=True),
    sa.Column('uptime', sa.String(), nullable=True),
    sa.Column('network_info', sa.String(), nullable=True),
    sa.Column('connections', sa.String(), nullable=True),
    sa.Column('swap_usage', sa.String(), nullable=True),
    sa.Column('error_logs', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_info_host'), 'system_info', ['host'], unique=False)
    op.create_index(op.f('ix_system_info_id'), 'system_info', ['id'], unique=False)
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_projects_title', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('advisor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('career', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    op.create_index('ix_projects_title', 'projects', ['title'], unique=False)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.drop_index(op.f('ix_system_info_id'), table_name='system_info')
    op.drop_index(op.f('ix_system_info_host'), table_name='system_info')
    op.drop_table('system_info')
    # ### end Alembic commands ###
